version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:808354265930:task-definition/first-run-task-definition:2"
        LoadBalancerInfo:
          ContainerName: "hello-world"
          ContainerPort: 80
